const ORDER_STATUS = {
  ORDER_RECEIVED: "ORDER_RECEIVED",
  IN_THE_KITCHEN: "IN_THE_KITCHEN",
  SENT_TO_DELIVERY: "SENT_TO_DELIVERY",
  DELIVERED: "DELIVERED",
};

const JWT_SECRET_KEY = "Secrect@007";

const CUSTOM_PRODUCT_ID = "635c18d80624b5338857658e";

const PIZZA_BASE = {
  BASE_1: "BASE_1",
  BASE_2: "BASE_2",
  BASE_3: "BASE_3",
  BASE_4: "BASE_4",
  BASE_5: "BASE_5",
};

const PIZZA_SAUCE = {
  SAUCE_1: "SAUCE_1",
  SAUCE_2: "SAUCE_2",
  SAUCE_3: "SAUCE_3",
  SAUCE_4: "SAUCE_4",
  SAUCE_5: "SAUCE_5",
};

const PIZZA_CHEESE = {
  CHEESE_1: "CHEESE_1",
  CHEESE_2: "CHEESE_2",
  CHEESE_3: "CHEESE_3",
  CHEESE_4: "CHEESE_4",
};

module.exports = {
  ORDER_STATUS,
  JWT_SECRET_KEY,
  PIZZA_BASE,
  PIZZA_SAUCE,
  PIZZA_CHEESE,
  CUSTOM_PRODUCT_ID,
};
